export const topicsData = [
  { id: 0, title: "Home", chapter: "Welcome", component: "Home" },
  { id: 1, title: "JS Hoisting", chapter: "JavaScript Fundamentals", component: "JSHoisting" },
  { id: 2, title: "Closure", chapter: "JavaScript Fundamentals", component: "Closure" },
  { id: 3, title: "Execution Stack", chapter: "JavaScript Fundamentals", component: "ExecutionStack" },
  { id: 4, title: "Single Threaded JS", chapter: "JavaScript Fundamentals", component: "SingleThreadedJS" },
  { id: 5, title: "Asynchronous Programming", chapter: "JavaScript Fundamentals", component: "AsyncProgramming" },
  { id: 6, title: "Promises, Await, and Async", chapter: "JavaScript Fundamentals", component: "PromisesAsync" },
  { id: 7, title: "Memory Leak", chapter: "Memory & Performance", component: "MemoryLeak" },
  { id: 8, title: "Web Workers", chapter: "Memory & Performance", component: "WebWorkers" },
  { id: 9, title: "Classes in JS", chapter: "Memory & Performance", component: "ClassesJS" },
  { id: 10, title: "ECMA 6 JavaScript", chapter: "Memory & Performance", component: "ECMA6" },
  { id: 11, title: "Injection Attacks", chapter: "Web Security", component: "InjectionAttacks" },
  { id: 12, title: "Web Security Best Practices", chapter: "Web Security", component: "SecurityBestPractices" },
  { id: 13, title: "Encryption", chapter: "Web Security", component: "Encryption" },
  { id: 14, title: "Hashing", chapter: "Web Security", component: "Hashing" },
  { id: 15, title: "Public-Key/Private-Key", chapter: "Web Security", component: "PublicPrivateKey" },
  { id: 16, title: "SSL Public Key/Private Key", chapter: "Web Security", component: "SSL" },
  { id: 17, title: "Cookies", chapter: "Web Security", component: "Cookies" },
  { id: 18, title: "Session, JWT, httpOnly", chapter: "Web Security", component: "SessionJWT" },
  { id: 19, title: "CRUD", chapter: "Data & APIs", component: "CRUD" },
  { id: 20, title: "RDBMS", chapter: "Data & APIs", component: "RDBMS" },
  { id: 21, title: "1:M Relationships", chapter: "Data & APIs", component: "OneToMany" },
  { id: 22, title: "M:M Relationships", chapter: "Data & APIs", component: "ManyToMany" },
  { id: 23, title: "1NF and 2NF", chapter: "Data & APIs", component: "Normalization" },
  { id: 24, title: "Creating Secure RESTful APIs", chapter: "Data & APIs", component: "RESTfulAPIs" },
  { id: 25, title: "Fetch", chapter: "Data & APIs", component: "Fetch" },
  { id: 26, title: "Ajax Calls in Depth", chapter: "Data & APIs", component: "Ajax" },
  { id: 27, title: "GET vs POST", chapter: "Data & APIs", component: "GetVsPost" },
  { id: 28, title: "Web Application Architectural Patterns", chapter: "Architecture Patterns", component: "ArchPatterns" },
  { id: 29, title: "Monolithic Architecture", chapter: "Architecture Patterns", component: "Monolithic" },
  { id: 30, title: "Microservices Architecture", chapter: "Architecture Patterns", component: "Microservices" },
  { id: 31, title: "Model-View-Controller (MVC)", chapter: "Architecture Patterns", component: "MVC" },
  { id: 32, title: "API-Centric Architectures", chapter: "Architecture Patterns", component: "APICentric" },
  { id: 33, title: "Serverless / FaaS", chapter: "Architecture Patterns", component: "Serverless" },
  { id: 34, title: "Content Delivery Network (CDN)", chapter: "Modern Web Infrastructure", component: "CDN" },
  { id: 35, title: "Single Sign-On", chapter: "Modern Web Infrastructure", component: "SingleSignOn" },
  { id: 36, title: "OAuth and Bearer Token", chapter: "Modern Web Infrastructure", component: "OAuth" },
  { id: 37, title: "Hosting LLM Models", chapter: "Modern Web Infrastructure", component: "HostingLLM" }
];