// topics/topicsData.js

export const topicsData = [
  { id: 0, title: "Home", component: "Home" },
  { id: 1, title: "JS Hoisting", component: "JSHoisting" },
  { id: 2, title: "Closure", component: "Closure" },
  { id: 3, title: "Execution Stack", component: "ExecutionStack" },
  { id: 4, title: "Single Threaded JS", component: "SingleThreadedJS" },
  { id: 5, title: "Asynchronous Programming", component: "AsyncProgramming" },
  { id: 6, title: "Promises, Await, and Async", component: "PromisesAsync" },
  { id: 7, title: "Memory Leak", component: "MemoryLeak" },
  { id: 8, title: "Web Workers", component: "WebWorkers" },
  { id: 9, title: "Classes in JS", component: "ClassesJS" },
  { id: 10, title: "ECMA 6 JavaScript", component: "ECMA6" },
  { id: 11, title: "Injection Attacks", component: "InjectionAttacks" },
  { id: 12, title: "Web Security Best Practices", component: "SecurityBestPractices" },
  { id: 13, title: "Encryption", component: "Encryption" },
  { id: 14, title: "Hashing", component: "Hashing" },
  { id: 15, title: "Public-Key/Private-Key", component: "PublicPrivateKey" },
  { id: 16, title: "SSL", component: "SSL" },
  { id: 17, title: "Cookies", component: "Cookies" },
  { id: 18, title: "Session, JWT, httpOnly", component: "SessionJWT" },
  { id: 19, title: "CRUD", component: "CRUD" },
  { id: 20, title: "RDBMS", component: "RDBMS" },
  { id: 21, title: "1:M Relationships", component: "OneToMany" },
  { id: 22, title: "M:M Relationships", component: "ManyToMany" },
  { id: 23, title: "1NF and 2NF", component: "Normalization" },
  { id: 24, title: "Creating Secure RESTful APIs", component: "RESTfulAPIs" },
  { id: 25, title: "Fetch", component: "Fetch" },
  { id: 26, title: "Ajax", component: "Ajax" },
  { id: 27, title: "GET vs POST", component: "GetVsPost" },
  { id: 28, title: "WebSockets & Real-Time Communication", component: "WebSockets" },
  { id: 29, title: "WebAssembly (WASM)", component: "WebAssembly" }
];